os: linux

dist: bionic

language: php

matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    #- php: 7.2
    #- php: 7.3
    - php: 7.4

env:
  HEROKU_APP_NAME: herodock
  HEROKU_REGISTRY_IMAGE: registry.heroku.com/herodock/web
  DOCKER_USERNAME: sineverba

before_install:
  - echo $PHP_VERSION
  - chmod +x ./.deploy/scripts/build.sh
  - chmod +x ./.deploy/scripts/test.sh
  - chmod +x ./.deploy/scripts/deploy.sh
  - chmod +x ./.deploy/scripts/publish_env.sh

install:
  - ./.deploy/scripts/build.sh
  - composer install

script:
  - vendor/bin/phpunit

after_success:
  - docker build --tag ${HEROKU_APP_NAME} --file ./.deploy/app/Dockerfile ".";
  - echo "$DOCKER_API_KEY" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker images
  - docker push $DOCKER_USERNAME/$HEROKU_APP_NAME
  - |
    if [[ $TRAVIS_PULL_REQUEST = false ]]; then
      ./.deploy/scripts/deploy.sh
    fi
  - |
    if [[ $TRAVIS_TAG != "" ]]; then
      ./.deploy/scripts/publish_env.sh
      docker push $DOCKER_USERNAME/$HEROKU_APP_NAME:$TRAVIS_TAG
    fi
