os: linux

dist: bionic

language: php

matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    #- php: 7.2
    #- php: 7.3
    - php: 7.4

env:
  HEROKU_APP_NAME: herodock
  HEROKU_REGISTRY_IMAGE: registry.heroku.com/herodock/web

before_install:
  - echo $PHP_VERSION
  - chmod +x ./.deploy/scripts/build.sh
  - chmod +x ./.deploy/scripts/test.sh
  - chmod +x ./.deploy/scripts/deploy.sh
  - chmod +x ./.deploy/scripts/publish_env.sh

install:
  - ./.deploy/scripts/build.sh
  - composer install

script:
  - vendor/bin/phpunit

after_success:
  - |
    if [[ $TRAVIS_PULL_REQUEST = false ]]; then
      ./.deploy/scripts/deploy.sh
    fi
  - |
    if [[ $TRAVIS_TAG != "" ]]; then
      ./.deploy/scripts/publish_env.sh
    fi
