os: linux

dist: bionic

language: php

matrix:
  # Fast finish allows to set the build as "finished" even if the "allow_failures" matrix elements are not finished yet.
  fast_finish: true
  include:
    #- php: 7.2
    #- php: 7.3
    - php: 7.4

env:
  HEROKU_APP_NAME: herodock
  HEROKU_REGISTRY_IMAGE: registry.heroku.com/herodock/web
  DOCKER_USERNAME: sineverba

before_install:
  - echo $TRAVIS_PHP_VERSION
  - |
    if [[ ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG != "") && $TRAVIS_PHP_VERSION == "7.4" ]]; then
      chmod +x ./.deploy/scripts/build.sh
      chmod +x ./.deploy/scripts/build-docker.sh
      chmod +x ./.deploy/scripts/test.sh
      chmod +x ./.deploy/scripts/deploy.sh
      chmod +x ./.deploy/scripts/deploy-docker.sh
      chmod +x ./.deploy/scripts/publish_env.sh
    fi

install:
  - |
    if [[ ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG != "") && $TRAVIS_PHP_VERSION == "7.4" ]]; then
      ./.deploy/scripts/build.sh
      ./.deploy/scripts/test.sh
    fi
  - composer install

script:
  - vendor/bin/phpunit

after_success:
  - |
    if [[ $TRAVIS_TAG != "" && $TRAVIS_PHP_VERSION == "7.4" ]]; then
      ./.deploy/scripts/deploy.sh
      ./.deploy/scripts/publish_env.sh
      ./.deploy/scripts/build-docker.sh
      ./.deploy/scripts/deploy-docker.sh
    fi
