version: 2.1
jobs:

  test-unit:
    docker:
      - image: circleci/php:8.0.3-cli-buster

    steps:
      - checkout
      - setup_remote_docker
      - run: composer install
      - run: vendor/bin/phpunit

  build:
    docker:
      - image: cimg/base:2020.01
    environment:
      HEROKU_REGISTRY_IMAGE: registry.heroku.com/herodock/web
      HEROKU_APP_NAME: herodock
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build --tag $HEROKU_REGISTRY_IMAGE --file ./docker-build/Dockerfile "."
      - run: mkdir -p ~/docker
      - run: docker save -o ~/docker/$HEROKU_APP_NAME.tar $HEROKU_REGISTRY_IMAGE
      - persist_to_workspace:
          root: ~/docker
          paths:
            - .

  test-docker:
    docker:
      - image: cimg/base:2020.01
    environment:
      HEROKU_REGISTRY_IMAGE: registry.heroku.com/herodock/web
      HEROKU_APP_NAME: herodock
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run: docker load -i /tmp/workspace/$HEROKU_APP_NAME.tar
      - run: docker run -d --name herodock -e "PORT=9876" -p 9876:9876 $HEROKU_REGISTRY_IMAGE
      - run: docker exec -it herodock php -i | grep "PHP Version => 8.0.3"
      - run: mkdir -p ~/docker
      - run: docker save -o ~/docker/$HEROKU_APP_NAME.tar $HEROKU_REGISTRY_IMAGE
      - persist_to_workspace:
          root: ~/docker
          paths:
            - .

  deploy:
    docker:
      - image: cimg/base:2020.01
    environment:
      HEROKU_REGISTRY_IMAGE: registry.heroku.com/herodock/web
      HEROKU_APP_NAME: herodock
      TAG: << pipeline.git.tag >>
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run: docker load -i /tmp/workspace/$HEROKU_APP_NAME.tar
      - run: docker login -u _ -p $HEROKU_API_KEY registry.heroku.com
      - run: docker push $HEROKU_REGISTRY_IMAGE
      - run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run: heroku container:release web -a $HEROKU_APP_NAME
      - run: heroku config:set TAG=${TAG} -a $HEROKU_APP_NAME
      

workflows:
  version: 2
  build-deploy:
    jobs:
      - test-unit
      - build:
          filters:
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /.*/  
      - test-docker:
          requires:
            - build
          filters:
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /.*/  
      - deploy:
          context:
            - HEROKU
          requires:
            - test-docker
          filters:
            # ignore any commit on any branch by default
            branches:
              ignore: /.*/
            # only act on version tags
            tags:
              only: /.*/  
