version: 2.1
jobs:
  test-unit:
    docker:
      - image: sineverba/php8xc:8.0.2

    steps:
      - checkout
      - run: composer install
      - run: vendor/bin/phpunit

workflows:
  version: 2
  build-deploy:
    jobs:
      - test-unit