version: 2.1
jobs:
  test-unit:
    docker:
      - image: sineverba/php8xc:8.0.2

    steps:
      - checkout
      - run: composer install
      - run: vendor/bin/phpunit

  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker build --tag registry.heroku.com/herodock/web \
          --file ./.deploy/app/Dockerfile "."
      - run: docker save -o ~/herodock.tar registry.heroku.com/herodock/web
      - persist_to_workspace:
          root: ~
          paths:
            - .

  test-docker:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: docker load -i /tmp/workspace/herodock.tar
      - run: docker run -d --name herodock -e "PORT=9876" -p 9876:9876 registry.heroku.com/herodock/web
      - run: docker exec -it herodock php -i | grep "PHP Version => 8.0.2"
      

workflows:
  version: 2
  build-deploy:
    jobs:
      - test-unit
      - build
      - test-docker:
          requires:
            - build
